//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod4LJT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mod4LJT.Properties.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOCK.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLIANCE.
        /// </summary>
        public static string Compliance {
            get {
                return ResourceManager.GetString("Compliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESTROYER.
        /// </summary>
        public static string Destroyer {
            get {
                return ResourceManager.GetString("Destroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEAVY TANK.
        /// </summary>
        public static string HeavyTank {
            get {
                return ResourceManager.GetString("HeavyTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUDGE.
        /// </summary>
        public static string Judge {
            get {
                return ResourceManager.GetString("Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUNK TANK.
        /// </summary>
        public static string JunkTank {
            get {
                return ResourceManager.GetString("JunkTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIGHT TANK.
        /// </summary>
        public static string LightTank {
            get {
                return ResourceManager.GetString("LightTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACHINE.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACHINE (ALL).
        /// </summary>
        public static string MachineAll {
            get {
                return ResourceManager.GetString("MachineAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDIUM TANK.
        /// </summary>
        public static string MediumTank {
            get {
                return ResourceManager.GetString("MediumTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMISE.
        /// </summary>
        public static string Minimise {
            get {
                return ResourceManager.GetString("Minimise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN.
        /// </summary>
        public static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYERSTATS.
        /// </summary>
        public static string PlayerStats {
            get {
                return ResourceManager.GetString("PlayerStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POWER.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARTILLERY.
        /// </summary>
        public static string SelfPropelledArtillery {
            get {
                return ResourceManager.GetString("SelfPropelledArtillery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TANK TYPE.
        /// </summary>
        public static string TankType {
            get {
                return ResourceManager.GetString("TankType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LJT REGULATION.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEAK POINT BOMB.
        /// </summary>
        public static string WeakPointBomb {
            get {
                return ResourceManager.GetString("WeakPointBomb", resourceCulture);
            }
        }
    }
}
